name: Azure 리소스 신청서
description: 새로운 리소스 그룹 배포 또는 기존 리소스 그룹 업데이트 요청
title: "[Apply] "
labels: ["Pending Review"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 프로젝트 정보
        프로젝트와 관련된 정보를 입력해주세요.

  - type: dropdown
    id: request-type
    attributes:
      label: 요청 유형
      description: 신규 프로젝트 생성 또는 기존 프로젝트 업데이트를 선택하세요
      options:
        - 신규 프로젝트 생성
        - 기존 프로젝트 업데이트
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 주의사항
        - **신규 프로젝트 생성**을 선택한 경우: 아래 '프로젝트명' 필드를 반드시 입력해주세요.
        - **기존 프로젝트 업데이트**를 선택한 경우: 아래 '기존 프로젝트 선택'에서 프로젝트를 선택해주세요.

  - type: input
    id: project-name
    attributes:
      label: 프로젝트명
      description: 신규 프로젝트 생성인 경우에만 입력하세요
      placeholder: 예시) project-a
    validations:
      required: false

  - type: dropdown
    id: existing-project
    attributes:
      label: 기존 프로젝트 선택
      description: 기존 프로젝트 업데이트인 경우에만 선택하세요
      options:
        - 선택하세요
        # 프로젝트 목록은 여기에 추가됩니다. GitHub Actions 워크플로우를 통해 이 파일이 업데이트됩니다.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 사용자 정보
        리소스에 접근 권한이 필요한 사용자를 입력해주세요. 이 정보는 인프라 배포 시 정책(policy)에 접근 권한을 부여하는 데 사용됩니다.
        
        **형식 안내**: 
        - 각 사용자를 "이름:아이디@kt.com" 형식으로 입력하세요
        - 여러 사용자는 쉼표(,)로 구분하거나 한 줄에 한 명씩 입력하세요
        - [전체 사용자 목록](링크주소)에서 정확한 사용자 정보를 확인할 수 있습니다

  - type: textarea
    id: user-info
    attributes:
      label: 사용자 목록
      description: 리소스에 접근할 사용자 정보를 입력하세요
      placeholder: |
        예시)
        홍길동:gildong@kt.com
        김철수:chulsoo@kt.com
        이영희:younghee@kt.com
        
        또는
        
        홍길동:gildong@kt.com, 김철수:chulsoo@kt.com, 이영희:younghee@kt.com
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 리소스 그룹 정보
        아래 정보를 정확히 입력해주세요. 이 정보는 자동화된 배포 프로세스에 사용됩니다.

  - type: input
    id: resource-group-name
    attributes:
      label: 리소스_그룹명
      description: 배포할 리소스 그룹의 이름을 입력하세요
      placeholder: 예시) rg-production-app1
    validations:
      required: true

  - type: textarea
    id: deployment-reason
    attributes:
      label: 배포 이유
      description: 이 리소스 그룹을 배포하거나 업데이트하는 이유를 상세히 설명해주세요
      placeholder: 배포 이유를 입력하세요...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 배포 세부 정보
        추가적인 배포 세부 사항이 있다면 아래에 작성해주세요.

  - type: dropdown
    id: environment
    attributes:
      label: 환경
      description: 배포 대상 환경을 선택하세요
      options:
        - 개발(Development)
        - 테스트(Test)
        - 스테이징(Staging)
        - 프로덕션(Production)
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 추가 정보
      description: 배포 과정에서 고려해야 할 추가 정보나 주의사항이 있다면 작성해주세요
      placeholder: 추가 정보를 입력하세요...
    validations:
      required: false