name: 리소스 그룹 배포 요청
description: 새로운 리소스 그룹 배포 또는 기존 리소스 그룹 업데이트 요청
title: "[Apply] "
labels: ["Pending Review"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 프로젝트 정보
        프로젝트와 관련된 정보를 입력해주세요.

  - type: dropdown
    id: request-type
    attributes:
      label: 요청 유형
      description: 신규 프로젝트 생성 또는 기존 프로젝트 업데이트를 선택하세요
      options:
        - 신규 프로젝트 생성
        - 기존 프로젝트 업데이트
    validations:
      required: true

  - type: input
    id: project-name  
    attributes:
      label: 프로젝트명
      description: 신규 프로젝트인 경우 프로젝트명을 입력하세요
      placeholder: 예시) project-a
    validations:
      required: false

  - type: dropdown
    id: existing-project
    attributes:
      label: 기존 프로젝트 선택
      description: 기존 프로젝트 업데이트인 경우 프로젝트를 선택하세요
      options:
        - 선택하세요
      dynamicOptions:
        source: projects
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 리소스 그룹 정보
        아래 정보를 정확히 입력해주세요. 이 정보는 자동화된 배포 프로세스에 사용됩니다.

  - type: input
    id: resource-group-name
    attributes:
      label: 리소스_그룹명
      description: 배포할 리소스 그룹의 이름을 입력하세요
      placeholder: 예시) rg-production-app1
    validations:
      required: true

  - type: textarea
    id: deployment-reason
    attributes:
      label: 배포 이유
      description: 이 리소스 그룹을 배포하거나 업데이트하는 이유를 상세히 설명해주세요
      placeholder: 배포 이유를 입력하세요...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 배포 세부 정보
        추가적인 배포 세부 사항이 있다면 아래에 작성해주세요.

  - type: dropdown
    id: environment
    attributes:
      label: 환경
      description: 배포 대상 환경을 선택하세요
      options:
        - 개발(Development)
        - 테스트(Test)
        - 스테이징(Staging)
        - 프로덕션(Production)
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 추가 정보
      description: 배포 과정에서 고려해야 할 추가 정보나 주의사항이 있다면 작성해주세요
      placeholder: 추가 정보를 입력하세요...
    validations:
      required: false