name: Terraform Destroy (OIDC)

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: '삭제할 리소스 그룹 이름'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="resource_group_name=${{ github.event.inputs.resource_group_name }}"


      ## 상태파일에서 값 추출 : 상태 파일에서 리소스 그룹 이름을 자동으로 추출하여 사용
      # - name: Extract Resource Group Name
      #   id: extract
      #   run: |
      #     RG_NAME=$(terraform state show 'azurerm_resource_group.example' -no-color | grep name | head -n 1 | awk -F= '{print $2}' | tr -d ' "')
      #     echo "resource_group_name=$RG_NAME" >> $GITHUB_ENV

      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve -var="resource_group_name=${{ env.resource_group_name }}"