name: 'Resource Group Pre-check'

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: number
        description: '이슈 번호'
    outputs:
      resource_group:
        description: '추출된 리소스 그룹 이름'
        value: ${{ jobs.Pre-Check.outputs.resource_group }}
      project_name:
        description: '프로젝트 이름'
        value: ${{ jobs.Pre-Check.outputs.project_name }}
      resource_group_exists:  
        description: '리소스 그룹 존재 여부'
        value: ${{ jobs.Pre-Check.outputs.resource_group_exists }}
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      GH_TOKEN:
        required: true

jobs:
  Pre-Check:
    runs-on: ubuntu-latest

    outputs:
      resource_group: ${{ steps.get-resource-group.outputs.resource_group }}
      resource_group_exists: ${{ steps.check-resource-group-exists.outputs.exists }}
      project_name: ${{ steps.extract-project-info.outputs.project_name }}
    
    steps:
      - name: Extract Project Information from Issue
        id: extract-project-info
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            // workflow_call에서 전달받은 issue_number 사용
            const issue_number = ${{ inputs.issue_number }};
            const repo = context.repo;
            
            // 이슈 상세 정보 가져오기
            const issue = await github.rest.issues.get({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: issue_number
            });
            
            let projectName = null;
            const issueBody = issue.data.body;
            
            // 이슈 본문에서 요청 유형과 프로젝트명 추출
            if (issueBody) {
              // 요청 유형 확인
              const requestTypeMatch = issueBody.match(/### 요청 유형\s*\n\n([^\n]+)/);
              const requestType = requestTypeMatch ? requestTypeMatch[1].trim() : null;
              console.log(`요청 유형: ${requestType}`);
              
              if (requestType === '신규 프로젝트 생성') {
                // 신규 프로젝트 생성인 경우 프로젝트명 필드에서 추출
                const projectNameMatch = issueBody.match(/### 프로젝트명\s*\n\n([^\n]+)/);
                if (projectNameMatch && projectNameMatch[1].trim() !== '') {
                  projectName = projectNameMatch[1].trim();
                  console.log(`✅ 신규 프로젝트명: ${projectName}`);
                } else {
                  console.log('⚠️ 신규 프로젝트 생성이지만 프로젝트명이 입력되지 않았습니다.');
                  
                  // 오류를 이슈에 코멘트로 추가
                  try {
                    await github.rest.issues.createComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: issue_number,
                      body: `### ❌ 프로젝트명 누락\n\n신규 프로젝트 생성을 선택하셨지만 프로젝트명이 입력되지 않았습니다. 프로젝트명을 입력해주세요.`
                    });
                  } catch (commentError) {
                    console.error('코멘트 추가 중 오류 발생:', commentError.message);
                  }
                }
              } else if (requestType === '기존 프로젝트 업데이트') {
                // 기존 프로젝트 업데이트인 경우 기존 프로젝트 선택 필드에서 추출
                const existingProjectMatch = issueBody.match(/### 기존 프로젝트 선택\s*\n\n([^\n]+)/);
                if (existingProjectMatch && existingProjectMatch[1].trim() !== '선택하세요') {
                  projectName = existingProjectMatch[1].trim();
                  console.log(`✅ 기존 프로젝트명: ${projectName}`);
                } else {
                  console.log('⚠️ 기존 프로젝트 업데이트이지만 프로젝트가 선택되지 않았습니다.');
                  
                  // 오류를 이슈에 코멘트로 추가
                  try {
                    await github.rest.issues.createComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: issue_number,
                      body: `### ❌ 프로젝트 선택 누락\n\n기존 프로젝트 업데이트를 선택하셨지만 프로젝트가 선택되지 않았습니다. 기존 프로젝트를 선택해주세요.`
                    });
                  } catch (commentError) {
                    console.error('코멘트 추가 중 오류 발생:', commentError.message);
                  }
                }
              } else {
                console.log('⚠️ 요청 유형을 확인할 수 없습니다.');
              }
            }
            
            if (!projectName) {
              console.log('⚠️ 프로젝트명을 추출할 수 없습니다.');
              core.setFailed('프로젝트명을 찾을 수 없습니다.');
            }
            
            console.log(`프로젝트명: ${projectName}`);
            core.setOutput('project_name', projectName || '');

      - name: Extract Resource Group from Issue (Issue Forms)
        id: get-resource-group
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            // workflow_call에서 전달받은 issue_number 사용
            const issue_number = ${{ inputs.issue_number }};
            const repo = context.repo;
            
            // 이슈 상세 정보 가져오기
            const issue = await github.rest.issues.get({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: issue_number
            });
            
            let resourceGroup = null;
            const issueBody = issue.data.body;
            
            // 새로운 이슈 템플릿 형식에서 리소스 그룹명 추출
            if (issueBody) {
              // 새 이슈 템플릿의 리소스 그룹명 필드 (resource-group-name)
              const resourceGroupMatch = issueBody.match(/### 리소스_그룹명\s*\n\n([^\n]+)/);
              if (resourceGroupMatch && resourceGroupMatch[1].trim() !== '') {
                resourceGroup = resourceGroupMatch[1].trim();
                console.log(`✅ Found resource group name from new template: ${resourceGroup}`);
              } else {
                // 이전 방식 시도 (이전 템플릿 지원을 위해 유지)
                const mainPatterns = [
                  /###\s+리소스_그룹명\s*([\s\S]*?)(?=###|$)/,
                  /리소스[_\s]그룹명:?\s*([a-zA-Z0-9_-]+)/i,
                  /resource\s+group:?\s*([a-zA-Z0-9_-]+)/i
                ];
                
                // 주요 패턴으로 검색
                for (const pattern of mainPatterns) {
                  const match = issueBody.match(pattern);
                  if (match && match[1]) {
                    resourceGroup = match[1].trim();
                    console.log(`✅ Found resource group name with pattern: ${resourceGroup}`);
                    break;
                  }
                }
                
                // 패턴 검색으로 찾지 못한 경우, 리소스 그룹 형식의 줄 찾기
                if (!resourceGroup) {
                  const lines = issueBody.split('\n');
                  for (const line of lines) {
                    const trimmedLine = line.trim();
                    // 리소스 그룹 명명 규칙에 맞는 줄 찾기 (공백 없고 적절한 문자로 구성)
                    if (/^[a-zA-Z0-9][a-zA-Z0-9_-]{2,62}$/.test(trimmedLine)) {
                      resourceGroup = trimmedLine;
                      console.log(`✅ Found potential resource group name: ${resourceGroup}`);
                      break;
                    }
                  }
                }
              }
            }
            
            // 리소스 그룹명 검증
            if (resourceGroup) {
              // Azure 리소스 그룹 명명 규칙 검증
              const validNamePattern = /^[a-zA-Z0-9\-_\.\(\)]+$/;
              if (!validNamePattern.test(resourceGroup)) {
                console.log(`❌ 유효하지 않은 리소스 그룹명: "${resourceGroup}"`);
                console.log('리소스 그룹명은 영문자, 숫자, 대시(-), 밑줄(_), 괄호(), 마침표(.)만 포함할 수 있습니다.');
                
                // 오류를 이슈에 코멘트로 추가
                try {
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue_number,
                    body: `### ❌ 유효하지 않은 리소스 그룹명\n\n리소스 그룹명 \`${resourceGroup}\`은(는) Azure 명명 규칙에 맞지 않습니다.\n\n리소스 그룹명은 영문자, 숫자, 대시(-), 밑줄(_), 괄호(), 마침표(.)만 포함할 수 있습니다.\n\n유효한 리소스 그룹명으로 다시 시도해주세요.`
                  });
                  console.log('리소스 그룹명 오류 메시지가 이슈에 코멘트로 추가되었습니다.');
                } catch (commentError) {
                  console.error('코멘트 추가 중 오류 발생:', commentError.message);
                }
                
                core.setFailed(`유효하지 않은 리소스 그룹명: ${resourceGroup}`);
                return;
              }
            }
            
            if (!resourceGroup) {
              core.setFailed('Resource Group name not found in the issue body');
              return;
            }
            
            console.log(`✅ Resource Group name: ${resourceGroup}`);
            core.setOutput('resource_group', resourceGroup);


      
      - name: 'Az CLI login with OIDC'
        id: azure-login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Check if Resource Group already exists
        id: check-resource-group-exists
        if: steps.get-resource-group.outputs.resource_group != ''
        run: |
          RESOURCE_GROUP="${{ steps.get-resource-group.outputs.resource_group }}"
          echo "리소스 그룹 '${RESOURCE_GROUP}' 존재 여부 확인 중..."
          
          # Azure CLI를 사용하여 리소스 그룹 존재 여부 확인
          EXISTS=$(az group exists --name "${RESOURCE_GROUP}")
          
          if [ "$EXISTS" = "true" ]; then
            echo "⚠️ 리소스 그룹 '${RESOURCE_GROUP}'이(가) 이미 존재합니다."
            echo "exists=true" >> $GITHUB_OUTPUT
            
            # 기존 리소스 그룹 정보 가져오기
            TAGS=$(az group show --name "${RESOURCE_GROUP}" --query tags -o json)
            LOCATION=$(az group show --name "${RESOURCE_GROUP}" --query location -o tsv)
            
            echo "위치: ${LOCATION}"
            echo "태그: ${TAGS}"
            
            # 이슈에 충돌 경고 코멘트 추가
            ISSUE_NUMBER="${{ inputs.issue_number }}"
            COMMENT_BODY="### ⚠️ 리소스 그룹 충돌 경고

            요청하신 리소스 그룹 \`${RESOURCE_GROUP}\`은(는) 이미 존재합니다.

            **기존 리소스 그룹 정보:**
            - 위치: \`${LOCATION}\`

            다른 리소스 그룹 이름을 사용하시거나, 기존 리소스 그룹을 재사용하시려면 이슈를 수정해주세요."
            
            # GitHub CLI가 설치되어 있지 않으면 설치
            if ! command -v gh &> /dev/null; then
              echo "GitHub CLI 설치 중..."
              curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
              sudo apt update
              sudo apt install gh
            fi
            
            # GitHub Token을 사용하여 로그인
            echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
            
            # 이슈에 코멘트 추가
            gh issue comment "${ISSUE_NUMBER}" --repo "${{ github.repository }}" --body "${COMMENT_BODY}"
            
          else
            echo "✅ 리소스 그룹 '${RESOURCE_GROUP}'이(가) 존재하지 않습니다. 생성 가능합니다."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Add Resource Group Summary
        run: |
          echo "## 리소스 그룹 및 프로젝트 검증 결과" >> $GITHUB_STEP_SUMMARY
          echo "- 이슈 번호: #${{ inputs.issue_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- 프로젝트명: **${{ steps.extract-project-info.outputs.project_name }}**" >> $GITHUB_STEP_SUMMARY
          echo "- 식별된 리소스 그룹: **${{ steps.get-resource-group.outputs.resource_group }}**" >> $GITHUB_STEP_SUMMARY
          echo "- 리소스 그룹 충돌: **${{ steps.check-resource-group-exists.outputs.exists == 'true' && '⚠️ 충돌 있음' || '✅ 충돌 없음' }}**" >> $GITHUB_STEP_SUMMARY